// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * requestAndAwaitGrant(connection: AriesCore.ConnectionRecord, timeoutMs?: number): Promise<AriesCore.MediationRecord>
 * @param {string} agent_key
 * @param {string} connection - json?
 * @param {Big} timeoutMs
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_mediationRecipient_requestAndAwaitGrant(agent_key, connection, timeoutMs) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");	//mandatory
		if(connection==null)return Promise.reject("Invalid connection parameter");	//mandatory
		try{
			connection=JSON.parse(connection);
		}catch(e){
			return Promise.reject("Argument connection is not a valid JSON object");
		}
		if(timeoutMs==null);														//optional
		if(timeoutMs!=null&&timeoutMs.toNumber()<0){
			return Promise.reject("Argument timeoutMs has an invalid value")
		}
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		let ret=null;
		      if(timeoutMs==null){
			ret=await agent.mediationRecipient.requestAndAwaitGrant(connection);
		}else if(timeoutMs!=null){
			ret=await agent.mediationRecipient.requestAndAwaitGrant(connection,timeoutMs.toNumber());
		}
		return Promise.resolve(JSON.stringify(ret));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
