// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * @returns {Promise.<string>}
 */
export async function jsa_cache_list() {
	// BEGIN USER CODE
	try{
		//todo:decycle
		return Promise.resolve(JSON.stringify(support.cache.list()));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
