// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * setPools(poolConfigs: AriesCore.IndyPoolConfig[]): void  
 * 
 * @param {string} agent_key
 * @param {string} poolConfigs
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_ledger_setPools(agent_key, poolConfigs) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(poolConfigs==null)return Promise.reject("Invalid poolConfigs parameter");										//mandatory
		try{
			poolConfigs=JSON.parse(poolConfigs);
		}catch(e){
			return Promise.reject("Argument poolConfigs is not a valid JSON");
		}
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		agent.ledger.setPools(poolConfigs);
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
