// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * https://github.com/hyperledger/aries-framework-javascript/blob/dbfebb4720da731dbe11efdccdd061d1da3d1323/packages/core/src/modules/credentials/CredentialsApi.ts
 * 
 *    * Delete a credential record by id, also calls service to delete from wallet
 *    *
 *    * @param credentialId the credential record id
 *    * @param options the delete credential options for the delete operation
 * deleteById(credentialRecordId: string, options?: DeleteCredentialOptions): Promise<void>
 * @param {string} agent_key
 * @param {string} credentialId
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_credentials_deleteById(agent_key, credentialId) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(credentialId==null)return Promise.reject("Invalid credentialId parameter");										//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		await agent.credentials.deleteById(credentialId);
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
