// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * findPresentationMessage(proofRecordId: string): Promise<Promise<AriesCore.V1PresentationMessage> | Promise<AriesCore.V2PresentationMessage>>
 * 
 * agent.proofs.findPresentationMessage(proofRecordId)
 * 
 * @param {string} agent_key
 * @param {string} proofRecordId - mandatory
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_proofs_findPresentationMessage(agent_key, proofRecordId) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)/*mandatory*/return Promise.reject("Invalid agent_key parameter");
		if(proofRecordId==null)/*mandatory*/return Promise.reject("Invalid proofRecordId parameter");
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(await agent.proofs.findPresentationMessage(proofRecordId)));
	}catch(e){
		console.error(e);
		return Promise.reject(e);
	}
	// END USER CODE
}
