// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * getById(outOfBandId: string): Promise<AriesCore.OutOfBandRecord>
 * The out of band record id
 * 
 * 
 * Retrieve a out of band record by id
 * 
 * @throws — {RecordNotFoundError} If no record is found
 * 
 * @return — The out of band record
 * @param {string} agent_key
 * @param {string} outOfBandId
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_oob_getById(agent_key, outOfBandId) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(outOfBandId==null)return Promise.reject("Invalid outOfBandId parameter");										//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(await agent.oob.getById(outOfBandId)));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
