// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * update(proofRecord: AriesCore.ProofExchangeRecord): Promise<void>
 * @param {string} agent_key
 * @param {string} proofRecord - json?
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_proofs_update(agent_key, proofRecord) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");		//mandatory
		if(proofRecord==null)return Promise.reject("Invalid proofRecord parameter");	//mandatory
		try{
			proofRecord=JSON.parse(proofRecord);
		}catch(e){
			return Promise.reject("Argument proofRecord is not a valid JSON object");
		}
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		await agent.proofs.update(proofRecord);
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
