// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from "../support/entidad";
// END EXTRA CODE

/**
 * open(walletConfig: AriesCore.WalletConfig): Promise<void>
 * 
 * note: the options are similar to those supplied for the walletConfig subobject when creating an agent using jsa_aries_agent_create
 * @param {string} agent_key
 * @param {string} walletConfig - json?
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_wallet_open(agent_key, walletConfig) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");		//mandatory
		if(walletConfig==null)return Promise.reject("Invalid walletConfig parameter");	//mandatory
		try{
			walletConfig=JSON.parse(walletConfig);
		}catch(e){
			return Promise.reject("Argument walletConfig is not a valid JSON object");
		}
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		await agent.wallet.open(options);
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
