// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * @param {string} value
 * @returns {Promise.<Big>}
 */
export async function jsa_cache_put(value) {
	// BEGIN USER CODE
	try{
		return Promise.resolve(new Big(support.cache.put(value)));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
