// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * findAllByQuery(query: AriesCore.Query<AriesCore.OutOfBandRecord>): Promise<AriesCore.OutOfBandRecord[]>
 * Retrieve all out of bands records by specified query param
 * 
 * @returns — List containing all out of band records matching specified query params
 * @param {string} agent_key
 * @param {string} query - json?
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_oob_findAllByQuery(agent_key, query) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(query==null)return Promise.reject("Invalid query parameter");										//mandatory
		try{
			query=JSON.parse(query);
		}catch(e){
			return Promise.reject("Argument query is not a valid JSON object");
		}
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(await agent.oob.findAllByQuery(query)));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
