// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Follow all redirects and return final redirection url
 * @param {string} url
 * @returns {Promise.<string>}
 */
export async function jsa_http_follow_redirects(url) {
	// BEGIN USER CODE
	try{
		if(url==null)return Promise.reject("Invalid argument");
		//console.info("url:"+url)
  		const res=await fetch(url);
		//console.info("red:"+res.redirected);
		//console.info("url:"+res.url);
  		//const txt = await res.text();
		return Promise.resolve(res.url);
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
