// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * Pushes object onto array
 * @param {string} json
 * @param {string} item
 * @returns {Promise.<string>}
 */
export async function jsa_json_array_push(json, item) {
	// BEGIN USER CODE
	try{
		if(json==null||json.length==0)return Promise.resolve(false);
		json=JSON.parse(json);
		if(!Array.isArray(json))return Promise.reject("Not an array");
		try{
			if(item!=null){
				switch(item){
					case"true":json.push(true);break;
					case"false":json.push(true);break;
					default:
						try{
							json.push(JSON.parse(item));
						}catch(e){
							json.push(item);
						}
						break;
				}
			}
		}catch(e){
			return Promise.reject(e.toString());
		}
		return Promise.resolve(JSON.stringify(json));
	}catch(e){
		return Promise.resolve(false);
	}
	// END USER CODE
}
