// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * getByThreadId(threadId: string): Promise<AriesCore.ConnectionRecord>
 * The thread id
 * 
 * 
 * Retrieve a connection record by thread id
 * 
 * @throws — {RecordNotFoundError} If no record is found
 * 
 * @throws — {RecordDuplicateError} If multiple records are found
 * 
 * @returns — The connection record
 * @param {string} agent_key
 * @param {string} threadId
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_connections_getByThreadId(agent_key, threadId) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(threadId==null)return Promise.reject("Invalid threadId parameter");										//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(await agent.connections.getByThreadId(threadId)));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
