// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * save({ content, tags, id }: SaveGenericRecordOption): Promise<GenericRecord>
 * @param {string} agent_key
 * @param {string} content - json?
 * @param {string} tags - json?
 * @param {string} id_ - string?
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_genericRecords_save(agent_key, content, tags, id_) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(content==null)return Promise.reject("Invalid content parameter");										//mandatory
		try{
			content=JSON.parse(content);
		}catch(e){
			return Promise.reject("Argument content is not a valid JSON object");
		}
		if(tags==null)return Promise.reject("Invalid tags parameter");										//mandatory
		try{
			tags=JSON.parse(tags);
		}catch(e){
			return Promise.reject("Argument tags is not a valid JSON object");
		}
		if(id_==null)return Promise.reject("Invalid id_ parameter");										//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(await agent.genericRecords.save(content,tags,id_)));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
