// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from "../support/entidad";
// END EXTRA CODE

/**
 * @param {string} agent_key
 * @param {string} questionAnswerRecordId
 * @param {string} response
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_modules_questionAnswer_sendAnswer(agent_key, questionAnswerRecordId, response) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");
		if(questionAnswerRecordId==null)return Promise.reject("Invalid questionAnswerRecordId parameter");
		if(response==null)return Promise.reject("Invalid response parameter");
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(
			await agent.modules.questionAnswer.sendAnswer(questionAnswerRecordId,response)
		));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
