// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from "../support/entidad";
// END EXTRA CODE

/**
 * @param {string} agent_key
 * @param {string} domain
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_oob_createLegacyInvitation(agent_key, domain) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");	//mandatory
		if(domain==null)return Promise.reject("Invalid domain parameter");	//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		const{invitation}=await agent.oob.createLegacyInvitation();
		let ret=invitation.toUrl({domain:domain});
		//return Promise.resolve(support.cache.put(ret));
		return Promise.resolve(ret);
	}catch(e){
		return Promise.reject(e.toString());
	}
	throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
