// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * registerInstance(token: AriesCore.InjectionToken<any>, instance: any): DependencyContainer
 * @param {string} agent_key
 * @param {string} token - json?
 * @param {string} instance - json?
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_injectionContainer_registerInstance(agent_key, token, instance) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(token==null)return Promise.reject("Invalid token parameter");										//mandatory
		try{
			token=JSON.parse(token);
		}catch(e){
			return Promise.reject("Argument token is not a valid JSON object");
		}
		if(instance==null)return Promise.reject("Invalid instance parameter");										//mandatory
		try{
			instance=JSON.parse(instance);
		}catch(e){
			return Promise.reject("Argument instance is not a valid JSON object");
		}
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(agent.injectionContainer.registerInstance(token,instance)));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
