// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * addConnectionType(connectionId: string, type: string): Promise<AriesCore.ConnectionRecord>
 * Allows for the addition of connectionType to the record. Either updates or creates an array of string connection types
 * 
 * @throws — {RecordNotFoundError} If no record is found
 * @param {string} agent_key
 * @param {string} connectionId
 * @param {string} type_
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_connections_addConnectionType(agent_key, connectionId, type_) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(connectionId==null)return Promise.reject("Invalid connectionId parameter");										//mandatory
		if(type_==null)return Promise.reject("Invalid type_ parameter");										//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(await agent.connections.addConnectionType(connectionId,type_)));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
