// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import {NativeModules} from 'react-native';
// END EXTRA CODE

/**
 * @param {string} path
 * @returns {Promise.<void>}
 */
export async function jsa_load(path) {
	// BEGIN USER CODE
	try{
		await NativeModules.Loadlib.load(path);
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
