// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * isRegistered(token: AriesCore.InjectionToken<any>, recursive?: boolean): boolean
 * The token to check
 * 
 * 
 * Check if the given dependency is registered
 * 
 * @return — Whether or not the token is registered
 * @param {string} agent_key
 * @param {string} token - json?
 * @param {boolean} recursive
 * @returns {Promise.<boolean>}
 */
export async function jsa_aries_agent_injectionContainer_isRegistered(agent_key, token, recursive) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(token==null)return Promise.reject("Invalid token parameter");										//mandatory
		try{
			token=JSON.parse(token);
		}catch(e){
			return Promise.reject("Argument token is not a valid JSON object");
		}
		if(recursive==null)return Promise.reject("Invalid recursive parameter");										//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(agent.injectionContainer.isRegistered(token,recursive));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
