// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * getRevocationRegistryDelta(revocationRegistryDefinitionId: string, fromSeconds?: number, toSeconds?: number): Promise<AriesCore.ParseRevocationRegistryDeltaTemplate>  
 * 
 * agent.ledger.getRevocationRegistryDelta()
 * 
 * @param {string} agent_key
 * @param {string} revocationRegistryDefinitionId
 * @param {Big} fromSeconds
 * @param {Big} toSeconds
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_ledger_getRevocationRegistryDelta(agent_key, revocationRegistryDefinitionId, fromSeconds, toSeconds) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");											//mandatory
		if(revocationRegistryDefinitionId==null)return Promise.reject("Invalid revocationRegistryDefinitionId parameter");	//mandatory
		if(fromSeconds==null)return Promise.reject("Invalid fromSeconds parameter");										//mandatory
		if(toSeconds==null)return Promise.reject("Invalid toSeconds parameter");											//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(await agent.ledger.getRevocationRegistryDelta(revocationRegistryDefinitionId,fromSeconds.toNumber(),toSeconds.toNumber())));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
