// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * createLegacyConnectionlessInvitation(config: { recordId: string; message: AriesCore.AgentMessage; domain: string; }): Promise<{ message: AriesCore.AgentMessage; invitationUrl: string; }>
 * @param {string} agent_key
 * @param {string} recordId
 * @param {string} message - json?
 * @param {string} domain
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_oob_createLegacyConnectionlessInvitation(agent_key, recordId, message, domain) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");		//mandatory
		if(recordId==null)return Promise.reject("Invalid recordId parameter");			//mandatory
		try{
			recordId=JSON.parse(recordId);
		}catch(e){
			return Promise.reject("Argument recordId is not a valid JSON object");
		}
		if(message==null)return Promise.reject("Invalid message parameter");			//mandatory
		if(domain==null)return Promise.reject("Invalid domain parameter");				//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		return Promise.resolve(JSON.stringify(await agent.oob.createLegacyConnectionlessInvitation(recordId,message,domain)));
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
