// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * https://github.com/hyperledger/aries-framework-javascript/blob/f27fb9921e11e5bcd654611d97d9fa1c446bc2d5/packages/core/src/modules/basic-messages/BasicMessagesApi.ts
 * 
 * getById(basicMessageRecordId: string): Promise<BasicMessageRecord>
 * The basic message record id
 * 
 * 
 * Retrieve a basic message record by id
 * 
 * @throws — {RecordNotFoundError} If no record is found
 * 
 * @return — The basic message record
 * @param {string} agent_key
 * @param {string} basicMessageRecordId
 * @returns {Promise.<string>}
 */
export async function jsa_aries_agent_basicMessages_getById(agent_key, basicMessageRecordId) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(basicMessageRecordId==null)return Promise.reject("Invalid basicMessageRecordId parameter");										//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		let basicMessageRecord=await agent.basicMessages.getById(basicMessageRecordId);
		return Promise.resolve(JSON.stringify(basicMessageRecord));

	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
