// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
import support from"../support/entidad";
// END EXTRA CODE

/**
 * setDefaultMediator(mediatorRecord: AriesCore.MediationRecord): Promise<void>
 * @param {string} agent_key
 * @param {string} mediatorRecord - json?
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_mediationRecipient_setDefaultMediator(agent_key, mediatorRecord) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(mediatorRecord==null)return Promise.reject("Invalid mediatorRecord parameter");										//mandatory
		try{
			mediatorRecord=JSON.parse(mediatorRecord);
		}catch(e){
			return Promise.reject("Argument mediatorRecord is not a valid JSON object");
		}
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		await agent.mediationRecipient.setDefaultMediator(mediatorRecord);
		return Promise.resolve();
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
