// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * public async removeConnectionType(connectionId: string, type: ConnectionType | string)
 * 
 * 
 *    * @param connectionId
 *    * @param type
 *    * @throws {RecordNotFoundError} If no record is found
 * 
 * https://github.com/hyperledger/aries-framework-javascript/blob/78ecf1ed959c9daba1c119d03f4596f1db16c57c/packages/core/src/modules/connections/ConnectionsApi.ts
 * @param {string} agent_key
 * @param {string} connectionId
 * @param {string} type_
 * @returns {Promise.<void>}
 */
export async function jsa_aries_agent_connections_removeConnectionType(agent_key, connectionId, type_) {
	// BEGIN USER CODE
	try{
		if(agent_key==null)return Promise.reject("Invalid agent_key parameter");										//mandatory
		if(connectionId==null)return Promise.reject("Invalid connectionId parameter");										//mandatory
		let agent=support.cache.get(agent_key);
		if(agent==null)return Promise.reject("Agent not found in cache");
		if(type_==null){
			return agent.connections.removeConnectionType(connectionId);
		}else{
			return agent.connections.removeConnectionType(connectionId,type_);
		}
	}catch(e){
		return Promise.reject(e.toString());
	}
	// END USER CODE
}
